# Generated by Django 5.2.11 on 2026-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='static_image',
            field=models.CharField(blank=True, help_text="Path to a static image (e.g., 'images/blog/thumb.jpg').", max_length=500, null=True),
        ),
    ]
