# Generated by Django 5.2.11 on 2026-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_static_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_it',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_it',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
